version: "3"
services:
  django:
    build: .
    image: joebach71/django-boilerplate:dev
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: "django"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: host.docker.internal
    volumes:
      - ./server:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "django"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

